---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_solo
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec
  sudo: false

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    data_bags_path: "cookbooks/workspace-setup/data_bags"
    run_list:
      - recipe[workspace-setup::packages]
      - recipe[workspace-setup::rbenv]
      - recipe[java]
      - recipe[workspace-setup::oh-my-zsh]
      - recipe[workspace-setup::dotfiles]
      - recipe[workspace-setup::vundle]
    attributes:
      java:
        install_flavor: "oracle"
        jdk_version: "8"
        oracle:
          accept_oracle_download_terms: true
    verifier:
      inspec_tests:
        - test/integration/default
